controller_panel:
  local_ip: "192.168.1.20"
  port: 5005
  map_port: 5006
  targets:
    - ip: "192.168.1.50"
      port: 5005
      map_port: 5006
    - ip: "192.168.1.51"
      port: 6005
      map_port: 6006
  send_hz: 100.0
  failsafe_timeout_ms: 150
  touch_device: ""
  no_touch_reader: false
  touch_swap_xy: false
  touch_invert_x: false
  touch_invert_y: false
  debug_touch: false

udp_receiver:
  bind_ip: "0.0.0.0"
  port: 5005
  map_port: 5006
  map_receiver_enabled: true
  control_hz: 100.0
  log_hz: 50.0
  log_format: "block"

udp_sender:
  local_ip: "192.168.1.20"
  targets:
    - ip: "192.168.1.50"
      port: 5005
      map_port: 5006
    - ip: "192.168.1.51"
      port: 6005
      map_port: 6006
  send_hz: 100.0
  failsafe_timeout_ms: 150

ros_udp_receiver:
  bind_ip: "0.0.0.0"
  port: 5005
  publish_hz: 100.0
  controller_topic: "/t0x0101_deck"
  tx_id_topic: "/aruco_comm/tx_id"
  tx_id_zero_frames: 3
  tx_id_value_frames: 1
  command_action_enabled: true
  command_action_server: "/command"
  command_action_type: "ares_deck_interfaces.action.Command"
  command_goal_field: "tx_id"
  command_wait_timeout_sec: 0.2
  debug_log: true
  debug_log_hz: 10.0
  debug_log_format: "block"
  debug_log_color: true
  button_to_tx_id: '{"ACTION_SELECT_3_LEFT": 1, "ACTION_SELECT_3_MID": 2, "ACTION_SELECT_3_RIGHT": 3, "ACTION_SELECT_2_LEFT": 4, "ACTION_SELECT_2_MID": 5, "ACTION_SELECT_2_RIGHT": 6, "ACTION_PLACE": 7}'
